# name: my workflow                       # Workflow 이름
# on: [push]                              # Event 감지

# jobs:                                   # Job 설정
#   build:                                # Job ID
#     name: hello github action           # Job 이름
#     runs-on: ubuntu-latest              # Job 가상환경 인스턴스
#     steps:                              # Steps
#       - name: checkout source code      # Step 이름
#         uses: actions/checkout@master   # Uses를 통한 외부 설정 가져오기: 자신의 레포지토리 소스 받아오기
#       - name: echo Hello                # Step 이름
#         run: echo "Hello"               # Run을 통한 스크립트 실행: Hello 출력

name: React Build
on:
  push:
    branches:                             # master Branch에서 push 이벤트가 일어났을 때만 실행
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.       # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Cache node modules          # node modules 캐싱
        uses: actions/cache@v1
        with:                             # with 구문으로 설정할 수 있는데, path와 key를 반드시 설정해주어야 함
          path: node_modules              # 저장하고 불러올 캐시 대상 폴더
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }} # 저장하고 불러올 때 식별할 수 있는 키 값
          restore-keys: |                 # 캐시 key가 일치하는 것이 없을 때, 차선택으로 캐싱 폴더를 찾는 key
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies        # 의존 파일 설치
        run: npm install

      - name: Build                       # React Build
        run: npm run build